### ISSUE TITLE
Can this lib support AIX OS and ppc64 ARCH?

### ISSUE THREAD

**Issue by gdtdpt** [elastic/go-txfile#39]
I want to cross compile filebeat to GOOS=aix GOARCH=ppc64 environment. 
I try to change some libs to the newest which had supported aix platform.
But I got an error from `../vendor/github.com/elastic/go-txfile/internal/vfs/osfs/lock_other.go:39:9: undefined: unix.Flock`.
I found that `unix.Flock` is from `golang.org/x/sys/unix` and `golang.org/x/sys/unix` lib has supported aix with the file names `zsyscall_aix_ppc64.go`.
But there is not `Flock` function in it and I don't know how to change `Flock` function to any other functions in `zsyscall_aix_ppc64.go`.

So I get stuck. Can anyone help me?

**Comment by urso** [comment]
I think on AIX you need fcntl to properly lock a file. This requires some more effort. On Windows go-txfile uses the github.com/gofrs/flock package. One could modify the internal osfs package to always use flock, independent on OS, or use it for windows and AIX only. Problem is: the flock package does not implement flock on AIX, but this PR introduces flock support for AIX: https://github.com/gofrs/flock/pull/40

**Comment by gdtdpt** [comment]
@urso thank you for your reply.
